//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmCentralWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int id { get; set; }
        public string name { get; set; }
        public string productType { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> dateRange { get; set; }
        public string farmerName { get; set; }
    }
}
